default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: ''
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: appland_test_development

test:
  <<: *default
  database: appland_test_test

production:
  <<: *default
  database: appland_test_production
  username: appland_test
  password: <%= ENV['APPLAND_TEST_DATABASE_PASSWORD'] %>
